### ISSUE TITLE
Cast Player to Entity

### ISSUE THREAD

**Issue by knugi** [btk5h/skript-mirror#102]
Hi, i must cast my variables {_e} to Entity, because i have method `setGlowing(org.bukkit.entity.Entity, org.inventivetalent.glow.GlowAPI.Color, org.bukkit.entity.Player)`

I try this code:

> import:
> 	org.inventivetalent.glow.GlowAPI as GlowAPI
> 	org.bukkit.entity.Entity as Entityy
> 	org.inventivetalent.glow.GlowAPI$Color as Kolory

> set {_e} to "jacek" parsed as offlineplayer
> set {_e} to [{_e} as Entityy]
> send "%{_e}.getClass()%"
> set {_x} to {GlowAPI}.setGlowing([{_e} as Entityy], Kolory.NONE!, player)

But send is org.bukkit.craftbukkit.v1_12_r!.entity.CraftPlayer and variables isn't org.bukkit.entity.Entity
How this cast to this type?

**Server information**
- skript-mirror: 0.19.1
- Skript: 2.2-dev36
- Bukkit: Spigot 1.12-R0.1-Snapshot
- Minecraft: 1.12 no mods
- Java: 8
- OS: Windows 10

**Comment by abandonedaccount6235** [comment]
You don't need to cast in skript-mirror

**Comment by knugi** [comment]
> You don't need to cast in skript-mirror

So in what?

**Comment by btk5h** [comment]
Casting objects in Java is required to tell the compiler that an object of a less specific type is actually an instance of a more specific type. Since skript-mirror knows the type of the object when the method is called, casting is not necessary.

Just pass the object to the method without casting it.
