### ISSUE TITLE
Custom syntaxes do not work on the newest versions of Bensku's Skript fork

### ISSUE THREAD

**Issue by Pikachu920** [btk5h/skript-mirror#25]
**Issue:**
Custom syntaxes do not work on the newest versions of Bensku's Skript fork (starting with dev30)
___
**Versions:**
- Skript 2.2-dev32d
- PaperSpigot 8b18730
- Minecraft 1.8.8
- skript-mirror 0.8.3
___
**Script:**
```
effect testing:
  stop

on script load:
  testing
```
___
**Output:**
```
[19:15:30 INFO]: [Skript] Reloading tests.sk...
[19:15:30 ERROR]: Can't understand this condition/effect: testing (tests.sk, line 5: testing')
[19:15:30 INFO]: [Skript] Encountered 1 error while reloading tests.sk!
```

**Comment by Snow-Pyon** [comment]
Shouldn't this be renamed to "Custom syntaxes don't work in the same file"?

**Comment by btk5h** [comment]
It appears this was caused by bensku/Skript@8efdb0a1803b30fb378df43d67f6ae1fba9ca15d. Script parsing has changed to parse the entire script before registering anything (even if async parsing is disabled).

If no one else will do it, I'll make a PR to use the old behavior when async parsing is disabled. (Might be a week or two before I'm free to tackle that, though.)
